# Generated by Django 6.0.3 on 2026-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shorturl_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
