# Generated by Django 6.0.3 on 2026-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
