# Generated by Django 6.0.3 on 2026-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shorturl_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
