# Generated by Django 6.0.3 on 2026-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_shorturl_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
