# Generated by Django 6.0.3 on 2026-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_remove_shorturl_qr_code_shorturl_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
